name: Build check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build EX-word addon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: |
          cd ..
          curl -sSfL https://github.com/MaxSignal/buildscripts/releases/download/Linux/devkitPro.tar.gz | tar -zxf -
          cd -
          DEVKITPRO="$OLDPWD/devkitPro" DEVKITSH4="$DEVKITPRO/devkitSH4" PATH="$DEVKITPRO/tools/bin:$DEVKITSH4/bin:$PATH" make
          test -e build/ja/HWDMP/hwdump.d01
